apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.13.3  # Versión específica del chart
    chart: sealed-secrets
    helm:
      releaseName: sealed-secrets
      values: |
        # Configuración personalizada para Sealed Secrets
        fullnameOverride: sealed-secrets-controller
        namespace: kube-system
        
        # Configuración de recursos
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        
        # Configuración de seguridad
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          fsGroup: 1001
        
        # Métricas para Prometheus
        metrics:
          dashboards:
            create: true
            namespace: monitoring
        
        # Configuración del controlador
        controller:
          create: true
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
        
        # RBAC
        rbac:
          create: true
          clusterRole: true
        
        # Service Account
        serviceAccount:
          create: true
          name: sealed-secrets-controller
  
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Health checks específicos para Sealed Secrets
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /status