apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-metrics
  namespace: kafka-system
  labels:
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: kafka
  endpoints:
  - port: jmx
    path: /metrics
    interval: 30s

---
# Service for exposing Kafka metrics
apiVersion: v1
kind: Service
metadata:
  name: kafka-metrics
  namespace: kafka-system
  labels:
    app: kafka
spec:
  ports:
  - name: jmx
    port: 5555
    targetPort: jmx
  selector:
    app: kafka

---
# NetworkPolicy para Kafka (opcional)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-network-policy
  namespace: kafka-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: kafka
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: torcal-ml
    - namespaceSelector:
        matchLabels:
          name: keda
    ports:
    - protocol: TCP
      port: 9092
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 9308  # Puerto de métricas
  egress:
  - to:
    - podSelector: {}
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80