apiVersion: v1
kind: PersistentVolume
metadata:
  name: torcal-ml-models-nfs-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs-server.torcal-ml.svc.cluster.local
    path: /nfsshare