
apiVersion: batch/v1
kind: Job
metadata:
  name: create-kafka-topic
  namespace: torcal-ml
spec:
  template:
    spec:
      containers:
      - name: kafka-client
        image: bitnami/kafka:latest
        command:
        - "/bin/bash"
        - "-c"
        - "kafka-topics.sh --bootstrap-server kafka.kafka-system.svc.cluster.local:9092 --create --if-not-exists --topic torcal-gpu-trigger --partitions 3 --replication-factor 1"
      restartPolicy: Never
  backoffLimit: 1
