
# argocd/secrets/postgres-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: torcal-ml
type: Opaque
data:
  username: dG9yY2FsdXNlcg==  # "torcaluser" en base64
  password: TzU2YjBiPnQvcjlhQzBJLC9Z  # Valor original de tu configuración
  database: dG9yY2Fs  # "torcal" en base64

---
# argocd/secrets/neo4j-secret.yaml
