apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torcal-ml-models-shared
  namespace: torcal-ml
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: torcal-ml-models-nfs-pv
  storageClassName: ""