apiVersion: apps/v1
kind: Deployment
metadata:
  name: torcal-ml
  namespace: torcal-ml
spec:
  selector:
    matchLabels:
      app: torcal-ml
  replicas: 1
  template:
    metadata:
      labels:
        app: torcal-ml
    spec:
      containers:
      - name: torcal-ml
        image: europe-southwest1-docker.pkg.dev/despliegue-458304/torcal-ml/torcal-ml-localhost@sha256:b76a5af176512efec657ee2ca28c0c3f91e6c9433622209751fd149f7ea94827
        volumeMounts:
        - name: env-config
          mountPath: /app/.env
          subPath: .env
        resources:
          limits:
            memory: "8Gi"
            cpu: "4000m"
          requests:
            memory: "6Gi"
            cpu: "6000m"
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database
        - name: NEO4J_URI
          value: "bolt://neo4j:7687"
        - name: NEO4J_USER
          value: "neo4j"
        - name: NEO4J_PASSWORD
          value: "password123"
        readinessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 20
      volumes:
      - name: env-config
        configMap:
          name: torcal-ml-env-config
       
