apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  namespace: torcal-ml
spec:
  selector:
    matchLabels:
      app: neo4j
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      serviceAccountName: neo4j-sa  # Añadir ServiceAccount
      securityContext:
        runAsNonRoot: true
        runAsUser: 7474  # UID del usuario neo4j
        fsGroup: 7474
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: neo4j
        image: neo4j:5.15
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 7474
          capabilities:
            drop:
              - ALL
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 7474
          name: http
        - containerPort: 7687
          name: bolt
        env:
        - name: NEO4J_AUTH
          valueFrom:
            secretKeyRef:
              name: neo4j-secret
              key: auth
        - name: NEO4J_server_config_strict__validation_enabled
          value: "false"
        - name: NEO4J_dbms_directories_mode
          value: "755"  # Cambiado de 777 a 755
        - name: NEO4J_dbms_connector_bolt_listen__address
          value: "0.0.0.0:7687"
        - name: NEO4J_dbms_connector_http_listen__address
          value: "0.0.0.0:7474"
        envFrom:
        - configMapRef:
            name: neo4j-config
        volumeMounts:
        - name: neo4j-data
          mountPath: /data
          subPath: data-dir
        - name: neo4j-logs
          mountPath: /logs
          subPath: logs-dir
        - name: neo4j-import
          mountPath: /var/lib/neo4j/import
          subPath: import-dir
        - name: neo4j-plugins
          mountPath: /plugins
          subPath: plugins-dir
        livenessProbe:
          httpGet:
            path: /
            port: 7474
          initialDelaySeconds: 45
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 7474
          initialDelaySeconds: 15
          periodSeconds: 5
      volumes:
      - name: neo4j-data
        persistentVolumeClaim:
          claimName: neo4j-data-pvc
      - name: neo4j-logs
        persistentVolumeClaim:
          claimName: neo4j-logs-pvc
      - name: neo4j-import
        persistentVolumeClaim:
          claimName: neo4j-import-pvc
      - name: neo4j-plugins
        persistentVolumeClaim:
          claimName: neo4j-plugins-pvc