apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: torcal-ml
data:
  postgresql.conf: |
    listen_addresses = '*'
    max_connections = 50
    superuser_reserved_connections = 3
    shared_buffers = 768MB
    work_mem = 16MB
    maintenance_work_mem = 96MB
    effective_cache_size = 2GB
    synchronous_commit = off
    wal_buffers = 8MB
    checkpoint_timeout = 10min
    max_wal_size = 512MB
    min_wal_size = 64MB
    random_page_cost = 1.5
    effective_io_concurrency = 4
    tcp_keepalives_idle = 60
    tcp_keepalives_interval = 10
    tcp_keepalives_count = 6
    idle_in_transaction_session_timeout = 30000
    statement_timeout = 60000
    lock_timeout = 30000
    default_statistics_target = 100
    log_min_error_statement = 'error'
    log_min_duration_statement = 2000
    log_connections = on
    log_disconnections = on
    log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '
    log_checkpoints = on
    log_lock_waits = on
    log_temp_files = 0
    autovacuum = on
    autovacuum_max_workers = 2
    autovacuum_naptime = 2min