# keda-scaledobj.yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ollama-scaler
  namespace: torcal-ml
spec:
  scaleTargetRef:
    name: ollama
    kind: Deployment
  minReplicaCount: 0
  maxReplicaCount: 1
  pollingInterval: 30
  cooldownPeriod: 300
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: torcal-ml-service:9092
      consumerGroup: ollama-consumer-group
      topic: gpu-trigger
      lagThreshold: "1"