apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keda-metrics
  namespace: keda
  labels:
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keda-operator-metrics-apiserver
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s

---
apiVersion: v1
kind: Service
metadata:
  name: keda-metrics
  namespace: keda
  labels:
    app.kubernetes.io/name: keda-operator-metrics-apiserver
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
  selector:
    app: keda-operator-metrics-apiserver