apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
  namespace: torcal-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
      - name: redpanda
        image: redpandadata/redpanda:latest
        # En lugar de pasar argumentos complejos, usemos la configuración por defecto
        command:
        - /bin/bash
        - -c
        - |
          mkdir -p /etc/redpanda
          cat > /etc/redpanda/redpanda.yaml << EOF
          redpanda:
            data_directory: /var/lib/redpanda/data
            seed_servers: []
            rpc_server:
              address: 0.0.0.0
              port: 33145
            kafka_api:
              - address: 0.0.0.0
                port: 9092
                advertised_address: torcal-ml-service
          EOF
          redpanda start --config /etc/redpanda/redpanda.yaml
        ports:
        - containerPort: 9092
          name: kafka
        volumeMounts:
        - name: redpanda-data
          mountPath: /var/lib/redpanda/data
      volumes:
      - name: redpanda-data
        emptyDir: {}