apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
  namespace: torcal-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
      - name: redpanda
        image: redpandadata/redpanda:v22.3.5
        command:
        - redpanda
        - start
        - --smp=1
        - --memory=1G
        - --reserve-memory=0M
        - --overprovisioned
        - --node-id=0
        - --kafka-addr=PLAINTEXT://0.0.0.0:9092
        - --advertise-kafka-addr=PLAINTEXT://torcal-ml-service:9092
        ports:
        - containerPort: 9092