apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-system
  namespace: argocd
  labels:
    app.kubernetes.io/name: kafka-system
    app.kubernetes.io/managed-by: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Blue-option/Torcal-Manifest
    targetRevision: main
    path: application-aws/kafka-system
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10