apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: torcal-ml
  labels:
    app: minio
    monitoring: "enabled"
spec:
  clusterIP: None
  ports:
  - port: 9000
    name: api
  - port: 9001
    name: console
  selector:
    app: minio