apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: torcal-ml
spec:
  serviceName: "minio-headless"
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
        monitoring: "enabled"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9000"
        prometheus.io/path: "/minio/v2/metrics/cluster"
    spec:
      serviceAccountName: minio-sa
      containers:
      - name: minio
        image: minio/minio:RELEASE.2025-04-22T22-12-26Z
        args:
        - server
        - /data
        - --console-address
        - ':9001'
        resources:
          limits:
            memory: "2Gi"
            cpu: "10000m"
          requests:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9001
          name: console
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: root-user
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: root-password
        - name: MINIO_DISK_USAGE_CRAWL_ENABLE
          value: "on"
        - name: MINIO_DISK_USAGE_THRESHOLD
          value: "98"
        # Enable Prometheus metrics
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          value: "public"
        volumeMounts:
        - name: data
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: api
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 20
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: api
          initialDelaySeconds: 5
          periodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
      storageClassName: gp3
