apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka-system
  labels:
    app.kubernetes.io/name: kafka-service
    app.kubernetes.io/managed-by: argocd
spec:
  selector:
    strimzi.io/cluster: kafka-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: kafka-cluster-kafka
  ports:
  - name: kafka-plain
    port: 9092
    targetPort: 9092