apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka-system
spec:
  kafka:
    version: 3.8.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      auto.create.topics.enable: true
      delete.topic.enable: true
      log.retention.hours: 24
      log.cleanup.policy: delete
      compression.type: snappy
    storage:
      type: persistent-claim
      size: 5Gi
      class: gp3
    resources:
      requests:
        memory: 1.5Gi
        cpu: 300m
      limits:  
        memory: 2.5Gi
        cpu: 800m
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: role
                  operator: In
                  values: [general]
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim  
      size: 3Gi
      class: gp3
    resources:
      requests:
        memory: 512Mi
        cpu: 100m
      limits:
        memory: 1Gi
        cpu: 300m
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: role
                  operator: In
                  values: [general]
  entityOperator:
    topicOperator: {}
    userOperator: {}