apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
  namespace: torcal-ml
spec:
  serviceName: "neo4j"
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      serviceAccountName: neo4j-sa
      containers:
      - name: neo4j
        image: neo4j:5.15
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 7474
          name: http
        - containerPort: 7687
          name: bolt
        env:
        - name: NEO4J_AUTH
          value: neo4j/password123
        - name: NEO4J_server_config_strict__validation_enabled
          value: "false"
        - name: NEO4J_dbms_directories_mode
          value: "777"
        - name: NEO4J_dbms_connector_bolt_listen__address
          value: "0.0.0.0:7687"
        - name: NEO4J_dbms_connector_http_listen__address
          value: "0.0.0.0:7474"
        envFrom:
        - configMapRef:
            name: neo4j-config
        volumeMounts:
        - name: data
          mountPath: /data
          subPath: data-dir
        - name: logs
          mountPath: /logs
          subPath: logs-dir
        - name: import
          mountPath: /var/lib/neo4j/import
          subPath: import-dir
        - name: plugins
          mountPath: /plugins
          subPath: plugins-dir
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
      storageClassName: standard
  - metadata:
      name: logs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
      storageClassName: standard
  - metadata:
      name: import
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
      storageClassName: standard
  - metadata:
      name: plugins
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard