apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  namespace: torcal-ml
spec:
  selector:
    matchLabels:
      app: neo4j
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      serviceAccountName: neo4j-sa
      containers:
      - name: neo4j
        image: neo4j:5.15
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 7474
          name: http
        - containerPort: 7687
          name: bolt
        env:
        - name: NEO4J_AUTH
          value: neo4j/password123
        # Añadir estas configuraciones para resolver los problemas
        - name: NEO4J_server_config_strict__validation_enabled
          value: "false"
        - name: NEO4J_dbms_directories_mode
          value: "777"
        # Protegerse contra las variables de entorno automáticas de Kubernetes
        - name: NEO4J_dbms_connector_bolt_listen__address
          value: "0.0.0.0:7687"
        - name: NEO4J_dbms_connector_http_listen__address
          value: "0.0.0.0:7474"
        envFrom:
        - configMapRef:
            name: neo4j-config
        volumeMounts:
        - name: neo4j-data
          mountPath: /data
          subPath: data-dir
        - name: neo4j-logs
          mountPath: /logs
          subPath: logs-dir
        - name: neo4j-import
          mountPath: /var/lib/neo4j/import
          subPath: import-dir
        - name: neo4j-plugins
          mountPath: /plugins
          subPath: plugins-dir
      volumes:
      - name: neo4j-data
        persistentVolumeClaim:
          claimName: neo4j-data-pvc
      - name: neo4j-logs
        persistentVolumeClaim:
          claimName: neo4j-logs-pvc
      - name: neo4j-import
        persistentVolumeClaim:
          claimName: neo4j-import-pvc
      - name: neo4j-plugins
        persistentVolumeClaim:
          claimName: neo4j-plugins-pvc