apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-config
  namespace: torcal-ml
data:
  NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
  NEO4J_apoc_export_file_enabled: "true"
  NEO4J_apoc_import_file_enabled: "true"
  NEO4J_apoc_import_file_use__neo4j__config: "true"