apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: torcal-ml
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      serviceAccountName: minio-sa
      containers:
      - name: minio
        image: minio/minio:RELEASE.2025-04-22T22-12-26Z
        args:
        - server
        - /data
        - --console-address
        - ':9001'
        resources:
          limits:
            memory: "8Gi"
            cpu: "4000m"
          requests:
            memory: "4Gi"
            cpu: "2000m"
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9001
          name: console
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: root-user
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: root-password
        - name: MINIO_DISK_USAGE_CRAWL_ENABLE
          value: "on"
        - name: MINIO_DISK_USAGE_THRESHOLD
          value: "98"
        volumeMounts:
        - name: minio-data
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: api
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 20
          failureThreshold: 3
      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-data-pvc