apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init
  namespace: torcal-ml
spec:
  template:
    spec:
      serviceAccountName: minio-sa
      containers:
      - name: minio-mc
        image: minio/mc
        command:
        - /bin/sh
        - -c
        - |
          # Esperar a que MinIO esté listo
          sleep 15
          
          # Configurar cliente - CORREGIDO el endpoint
          /usr/bin/mc config host add myminio http://minio.torcal-ml.svc.cluster.local:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
          
          # Crear buckets
          /usr/bin/mc mb -p myminio/torcal-models
          /usr/bin/mc mb -p myminio/torcal-data
          
          # Crear directorios importantes (usar mb con paths completos)
          /usr/bin/mc mb -p myminio/torcal-models/models/
          /usr/bin/mc mb -p myminio/torcal-models/jobs/status/
          /usr/bin/mc mb -p myminio/torcal-models/checkpoints/
          /usr/bin/mc mb -p myminio/torcal-models/logs/
          
          # Configurar políticas (usando anonymous en lugar de policy set)
          /usr/bin/mc anonymous set download myminio/torcal-models
          /usr/bin/mc anonymous set download myminio/torcal-data
          
          echo 'MinIO buckets created and configured successfully'
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: root-user
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: root-password
      restartPolicy: OnFailure