apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: torcal-ml
  labels:
    app: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
    spec:
      # Wait for PostgreSQL to be ready
      initContainers:
      - name: wait-for-postgres
        image: postgres:15-alpine
        env:
        - name: PGHOST
          value: "postgres"
        - name: PGPORT
          value: "5432"
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database
        command:
        - /bin/sh
        - -c
        - |
          echo "Esperando a que PostgreSQL esté disponible..."
          until pg_isready -h $PGHOST -p $PGPORT -U $PGUSER -d $PGDATABASE; do
            echo "PostgreSQL no está listo - esperando..."
            sleep 2
          done
          echo "PostgreSQL está listo!"
      containers:
      - name: postgres-exporter
        image: prometheuscommunity/postgres-exporter:v0.15.0
        ports:
        - containerPort: 9187
          name: metrics
        env:
        # Usar el formato de conexión PostgreSQL nativo (key=value)
        - name: DATA_SOURCE_NAME
          value: "host=postgres port=5432 user=$(POSTGRES_USER) password=$(POSTGRES_PASSWORD) dbname=$(POSTGRES_DB) sslmode=disable"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database
        # Expandir variables en DATA_SOURCE_NAME
        command:
        - /bin/sh
        - -c
        - |
          # Expandir las variables de entorno en DATA_SOURCE_NAME
          export DATA_SOURCE_NAME="host=postgres port=5432 user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} sslmode=disable"
          echo "Conectando a PostgreSQL con DSN: host=postgres port=5432 user=${POSTGRES_USER} dbname=${POSTGRES_DB} sslmode=disable"
          exec /bin/postgres_exporter
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9187
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9187
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5