apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: torcal-ml-services
  namespace: monitoring
spec:
  selector:
    matchLabels:
      monitoring: "enabled"
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
  namespaceSelector:
    matchNames:
    - torcal-ml
    - argocd