apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: torcal-ml-ingress
  namespace: torcal-ml
  annotations:
    kubernetes.io/ingress.class: "gce"
    # Configuraciones para optimizar rendimiento
    kubernetes.io/ingress.allow-http: "true"
    networking.gke.io/v1beta1.FrontendConfig: "torcal-ml-frontend-config"
    # Opcional: para habilitar IP estática
    # kubernetes.io/ingress.global-static-ip-name: "torcal-ml-ip"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: torcal-ml
            port:
              number: 80
  # Opcional: habilitar HTTPS
  # tls:
  # - secretName: torcal-ml-tls-cert