apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: torcal-ml
  labels:
    app: neo4j
spec:
  clusterIP: None
  ports:
  - port: 7474
    name: http
  - port: 7687
    name: bolt
  selector:
    app: neo4j