apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: torcal-ml
spec:
  replicas: 0 # KEDA lo escalará
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        env:
        - name: OLLAMA_NUM_PARALLEL
          value: "3"  # Reducir a 1 para evitar contención
        - name: OLLAMA_MAX_LOADED_MODELS
          value: "2"  # Cargar solo 1 modelo a la vez
        - name: OLLAMA_KEEP_ALIVE
          value: "30m"  # Mantener modelo en memoria más tiempo
        - name: OLLAMA_GPU_OVERHEAD
          value: "0"  # Sin overhead de GPU
        - name: OLLAMA_NUM_GPU
          value: "1"
        - name: OLLAMA_FLASH_ATTENTION
          value: "true"  # Usar Flash Attention si está disponible
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        ports:
        - containerPort: 11434
        command: ["/bin/sh"]
        args: 
          - "-c"
          - |
            # Iniciar Ollama en background
            ollama serve &
            # Esperar a que el servicio esté disponible
            echo "Esperando a que Ollama esté disponible..."
            sleep 10
            # Intentar descargar el modelo gemma3:4b
            echo "Descargando modelo gemma3:4b..."
            ollama pull gemma3:4b
            ollama pull bge-m3
            echo "Modelo gemma3:4b descargado y listo."
            # Mantener el contenedor ejecutándose
            wait
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "16Gi"
            cpu: "7000m"
          requests:
            nvidia.com/gpu: 1
            memory: "8Gi"
            cpu: "4000m"
      nodeSelector:
        gpu: "true"
        cloud.google.com/gke-accelerator: nvidia-l4
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "present"
        effect: "NoSchedule"
      - key: "cloud.google.com/gke-accelerator"
        operator: "Equal"
        value: "present"
        effect: "NoSchedule"