apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: torcal-ml
spec:
  replicas: 1  # KEDA lo escalará desde 0
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      initContainers:
      - name: model-loader
        image: ollama/ollama:latest
        command: ["/bin/bash", "-c"]
        args:
          - |
            mkdir -p /root/.ollama
            ollama serve &
            SERVER_PID=$!
            
            echo "Esperando a que Ollama inicie..."
            until curl -s http://localhost:11434/api/tags > /dev/null 2>&1; do
              sleep 2
              echo "."
            done
            
            echo "Descargando gemma3:4b..."
            ollama pull gemma3:4b
            
            kill $SERVER_PID
            wait $SERVER_PID
        volumeMounts:
        - name: ollama-models
          mountPath: /root/.ollama
        resources:
          limits:
            memory: "8Gi"
            cpu: "2000m"
          requests:
            memory: "4Gi"
            cpu: "1000m"
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
        env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "8Gi"
            cpu: "3500m"
          requests:
            memory: "4Gi"
            cpu: "2000m"
        volumeMounts:
        - name: ollama-models
          mountPath: /root/.ollama
        readinessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 10
          periodSeconds: 5
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
      tolerations:
      - key: "cloud.google.com/gke-accelerator"
        operator: "Equal"
        value: "present"
        effect: "NoSchedule"
      volumes:
      - name: ollama-models
        persistentVolumeClaim:
          claimName: ollama-pvc