apiVersion: v1
kind: Service
metadata:
  name: torcal-ml
  namespace: torcal-ml
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-west-1:ACCOUNT:certificate/CERTIFICATE-ID
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
spec:
  selector:
    app: torcal-ml
  ports:
  - name: https
    port: 443          # Puerto público HTTPS
    targetPort: 8000   # Tu aplicación sigue en 8000
    protocol: TCP
  - name: http
    port: 80           # Puerto HTTP (opcional)
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer