apiVersion: v1
kind: ConfigMap
metadata:
  name: torcal-ml-env-config
  namespace: torcal-ml
data:
  .env: |
    MODELO_TAXONOMIA=gemma3:4b
    NEO4J_URI=bolt://neo4j:7687
    NEO4J_USER=neo4j
    NEO4J_PASSWORD=password123
    DATABASE_URL=postgresql://torcaluser:O56b0b>t/r9aC0I,/Y@postgres:5432/torcal
    OLLAMA_URL=http://ollama.torcal-ml.svc.cluster.local:11434
    MODELO_TAXONOMIA=gemma3:4b
    
    KAFKA_BOOTSTRAP_SERVERS=kafka.kafka-system.svc.cluster.local:9092
    KAFKA_TOPIC_PREFIX=torcal-
    
    # Tokens para endpoints de Database Testing
    TOKEN_DB_TEST_NEO4J=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_DB_TEST_SQL=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_DB_CLEAR_NEO4J=B1OyOhL3X7ixkJAOwWzpUT
    
    # Tokens para endpoints de Model Management
    TOKEN_MODELS_TRAIN=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_MODELS_STATUS=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_MODELS_RESUME=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_MODELS_PAUSE=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_MODELS_DELETE=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_MODELS_LIST=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_MODELS_DIRECT_STATUS=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_USERS_ADD_BATCH=B1OyOhL3X7ixkJAOwWzpUT

    
    # Tokens para endpoints de User Management
    TOKEN_USERS_IMPORT_HISTORY=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_USERS_ADD_RECORD=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_USERS_GET_HISTORY=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_MODELS_ADD_QUESTIONS=B1OyOhL3X7ixkJAOwWzpUT

    
    # Tokens para endpoints de Clustering
    TOKEN_CLUSTERING_USER=B1OyOhL3X7ixkJAOwWzpUT
    
    # Tokens para endpoints de DQN
    TOKEN_DQN_TRAIN=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_MODELS_GRAPH_PARAMETERS=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_DQN_RECOMMEND_BLOCK=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_DQN_TOPIC_TEST=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_DQN_INITIAL_EVALUATION=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_DQN_LIST_MODELS=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_DQN_EVALUATE=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_DQN_CLEAR_HISTORY=B1OyOhL3X7ixkJAOwWzpUT


    #Tokens de test
    TOKEN_USERS_LIST=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_USERS_DELETE=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_USERS_DELETE_MULTIPLE=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_USERS_CREATE=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_DB_TEST_MINIO=B1OyOhL3X7ixkJAOwWzpUT


    TOKEN_QUESTIONS_GET_METADATA=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_QUESTIONS_UPDATE_STATUS=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_QUESTIONS_UPDATE_METADATA=B1OyOhL3X7ixkJAOwWzpUT


    TOKEN_DB_TEST_NEO4J=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_DB_TEST_SQL=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_DB_TEST_MINIO=B1OyOhL3X7ixkJAOwWzpUT
    TOKEN_MODELS_GRAPH_PARAMETERS=B1OyOhL3X7ixkJAOwWzpUT

    MINIO_ENDPOINT=minio:9000
    MINIO_ACCESS_KEY=torcaladmin
    MINIO_SECRET_KEY=6fDVW1Hw55U2rbMOR16Bmmrx
    MINIO_USE_SSL=false
    MINIO_BUCKET_MODELS=torcal-models
    MINIO_BUCKET_DATA=torcal-data

    TOKEN_TOPICS_LIST=B1OyOhL3X7ixkJAOwWzpUT
    