apiVersion: v1
kind: Service
metadata:
  name: torcal-ml
  namespace: torcal-ml
spec:
  selector:
    app: torcal-ml
  ports:
  - name: https
    port: 443
    targetPort: 8000
    protocol: TCP
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer
