# kafka-simple.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka-system
spec:
  kafka:
    version: 3.8.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      # Configuración básica para single-replica
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      
      # Configuración para tu caso de uso
      auto.create.topics.enable: true
      delete.topic.enable: true
      log.retention.hours: 24
      log.segment.bytes: 268435456
      log.cleanup.policy: delete
      compression.type: snappy
      
    storage:
      type: persistent-claim
      size: 5Gi
      class: gp3
      deleteClaim: false
      
    # Recursos optimizados
    resources:
      requests:
        memory: 1.5Gi
        cpu: 300m
      limits:  
        memory: 2.5Gi
        cpu: 800m
      
    # Scheduling en nodos generales
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: role
                  operator: In
                  values: [general]
                  
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim  
      size: 3Gi
      class: gp3
      deleteClaim: false
      
    # Recursos para Zookeeper
    resources:
      requests:
        memory: 512Mi
        cpu: 100m
      limits:
        memory: 1Gi
        cpu: 300m
      
    # Scheduling en nodos generales  
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: role
                  operator: In
                  values: [general]
                  
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 256Mi
          cpu: 100m
    userOperator:
      resources:
        requests:
          memory: 128Mi
          cpu: 50m  
        limits:
          memory: 256Mi
          cpu: 100m
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: role
                  operator: In
                  values: [general]