apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: torcal-ml
spec:
  destination:
    name: ''
    namespace: torcal-ml
    server: 'https://kubernetes.default.svc'
  source:
    path: application-aws
    repoURL: 'https://github.com/Blue-option/Torcal-Manifest'
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

k8s-elb-a8ed664336ee44385a020f2fb20516cc
k8s-elb-a7f69878f84da4e3c891da3a8496c9e1