apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 26.4.0
    chart: kafka
    helm:
      values: |
        replicaCount: 1
        
        # Use KRaft mode (no Zookeeper)
        kraft:
          enabled: true
          
        # Disable Zookeeper entirely
        zookeeper:
          enabled: false
        
        # Properly configure listeners
        listeners:
          client:
            protocol: PLAINTEXT
            containerPort: 9092
          controller:
            protocol: PLAINTEXT
            containerPort: 9093
        
        # Configure probes properly
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 120
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 3
        
        # Persistence configuration
        persistence:
          enabled: true
          size: 10Gi
          storageClass: standard
        
        # Resource allocation
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        
        # Security configuration
        auth:
          clientProtocol: plaintext
          interBrokerProtocol: plaintext
          
        # Importante: habilita la creación automática de topics
        extraEnvVars:
          - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
          - name: KAFKA_CFG_DELETE_TOPIC_ENABLE
            value: "true"

  destination:
    server: https://kubernetes.default.svc
    namespace: kafka-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true