
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/Blue-option/Torcal-Manifest
    targetRevision: main
    path: infrastructure/configs/kafka/base
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true