apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 26.4.0
    chart: kafka
    helm:
      values: |
        replicaCount: 1
        
        # Use KRaft mode (no Zookeeper)
        kraft:
          enabled: true
        zookeeper:
          enabled: false
        
        # Properly configure listeners
        listeners:
          client:
            protocol: PLAINTEXT
            containerPort: 9092
          controller:
            protocol: PLAINTEXT
            containerPort: 9093
        
        # Configure probes properly
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 120
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 3
        
        # Persistence configuration
        persistence:
          enabled: true
          size: 10Gi
          storageClass: standard-rwo
          # Set appropriate permissions on the mount
          mountPath: /bitnami/kafka
        
        # Resource allocation
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        
        # Security configuration
        auth:
          clientProtocol: plaintext
          interBrokerProtocol: plaintext
        
        # Security context
        containerSecurityContext:
          runAsUser: 1001
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        podSecurityContext:
          enabled: true
          fsGroup: 1001
          runAsUser: 1001
        
        # Volume permissions
        volumePermissions:
          enabled: true
          image:
            registry: docker.io
            repository: bitnami/bitnami-shell
            tag: latest
          securityContext:
            runAsUser: 0
        
        # Metrics
        metrics:
          kafka:
            enabled: true
        
        # Init container for volume permissions
        initContainers:
          - name: volume-permissions
            image: docker.io/bitnami/bitnami-shell:latest
            command:
              - /bin/bash
              - -ec
              - |
                mkdir -p /bitnami/kafka/data /bitnami/kafka/config
                chmod -R 700 /bitnami/kafka/
                chown -R 1001:1001 /bitnami/kafka/
            securityContext:
              runAsUser: 0
            volumeMounts:
              - name: data
                mountPath: /bitnami/kafka
        
        serviceAccount:
          create: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true